### ISSUE TITLE
[ mainPage ] - header

### ISSUE THREAD

**Issue by myeongheonhong** [Track1-client/client#3]
### ✅ 담당 페이지 & 기능
- [x] 로고 이미지
- [x] 슬로건
- [x] 마이페이지 버튼

**Comment by NaveOWO** [comment]
첫 이슈 축하드려요
라고 할라그랬는데 첫 이슈 아니네 ㅋ ㅋ ㅋㅋㅋ ㅋㅋ

**Comment by myeongheonhong** [comment]
잘부탁드립니다 리드개발자님~~ 라벨도 잘 달아놓을게요!!
